eureka:
  client:
    region: us-east-1
    availability-zones:
      us-east-1: us-east-1c,us-east-1b
    serviceUrl:
      defaultZone: http://ec2-54-80-121-92.compute-1.amazonaws.com:8761/eureka/
      us-east-1c: http://ec2-54-80-121-92.compute-1.amazonaws.com:8761/eureka/
      us-east-1b: http://ec2-54-82-95-143.compute-1.amazonaws.com:8761/eureka/
  datacenter: cloud